# Generated by Django 5.1.7 on 2025-11-11 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('passage', models.TextField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_tests', to='core.level')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_tests', to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('correct_answer', models.CharField(blank=True, max_length=5, null=True)),
                ('reading_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingtest')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('reading_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='reading.readingtest')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reading/ads/')),
                ('reading_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reading.readingtest')),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('reading_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='reading.readingtest')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text_before', models.TextField(blank=True, null=True)),
                ('gap_number', models.PositiveIntegerField(blank=True, null=True)),
                ('text_after', models.TextField(blank=True, null=True)),
                ('reading_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='reading.readingtest')),
            ],
        ),
    ]
