# Generated by Django 5.1.7 on 2025-11-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SampleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('preparation', models.CharField(max_length=50)),
                ('speaking', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('task_types', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SampleQuestionGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sample_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='speaking.samplequestion')),
            ],
        ),
    ]
